version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 99
